# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drawer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(10, 20, 621, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.general_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.general_horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.general_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.general_horizontalLayout.setObjectName("general_horizontalLayout")
        self.image_list_widget = QtWidgets.QWidget(self.horizontalWidget)
        self.image_list_widget.setObjectName("image_list_widget")
        self.Image_list_widget = QtWidgets.QVBoxLayout(self.image_list_widget)
        self.Image_list_widget.setContentsMargins(0, 0, 0, 0)
        self.Image_list_widget.setObjectName("Image_list_widget")
        self.image_list_lbl = QtWidgets.QLabel(self.image_list_widget)
        self.image_list_lbl.setObjectName("image_list_lbl")
        self.Image_list_widget.addWidget(self.image_list_lbl)
        self.image_list = QtWidgets.QListWidget(self.image_list_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_list.sizePolicy().hasHeightForWidth())
        self.image_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.image_list.setFont(font)
        self.image_list.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.image_list.setObjectName("image_list")
        self.Image_list_widget.addWidget(self.image_list)
        self.image_list_buttons_layout = QtWidgets.QGridLayout()
        self.image_list_buttons_layout.setObjectName("image_list_buttons_layout")
        self.drawMode_switch = QtWidgets.QPushButton(self.image_list_widget)
        self.drawMode_switch.setObjectName("drawMode_switch")
        self.image_list_buttons_layout.addWidget(self.drawMode_switch, 0, 0, 1, 1)
        self.import_images = QtWidgets.QPushButton(self.image_list_widget)
        self.import_images.setObjectName("import_images")
        self.image_list_buttons_layout.addWidget(self.import_images, 1, 0, 1, 1)
        self.remove_image = QtWidgets.QPushButton(self.image_list_widget)
        self.remove_image.setObjectName("remove_image")
        self.image_list_buttons_layout.addWidget(self.remove_image, 1, 1, 1, 1)
        self.view_tei = QtWidgets.QPushButton(self.image_list_widget)
        self.view_tei.setObjectName("view_tei")
        self.image_list_buttons_layout.addWidget(self.view_tei, 0, 1, 1, 1)
        self.load_image = QtWidgets.QPushButton(self.image_list_widget)
        self.load_image.setObjectName("load_image")
        self.image_list_buttons_layout.addWidget(self.load_image, 2, 0, 1, 2)
        self.Image_list_widget.addLayout(self.image_list_buttons_layout)
        self.general_horizontalLayout.addWidget(self.image_list_widget)
        self.image_viewer_widget_2 = QtWidgets.QWidget(self.horizontalWidget)
        self.image_viewer_widget_2.setObjectName("image_viewer_widget_2")
        self.image_viewer_widget = QtWidgets.QVBoxLayout(self.image_viewer_widget_2)
        self.image_viewer_widget.setContentsMargins(0, 0, 0, 0)
        self.image_viewer_widget.setObjectName("image_viewer_widget")
        self.image_area_lbl = QtWidgets.QLabel(self.image_viewer_widget_2)
        self.image_area_lbl.setObjectName("image_area_lbl")
        self.image_viewer_widget.addWidget(self.image_area_lbl)
        self.image_viewer = QtWidgets.QGraphicsView(self.image_viewer_widget_2)
        self.image_viewer.setObjectName("image_viewer")
        self.image_viewer_widget.addWidget(self.image_viewer)
        self.general_horizontalLayout.addWidget(self.image_viewer_widget_2)
        self.text_viewer_widget = QtWidgets.QWidget(self.horizontalWidget)
        self.text_viewer_widget.setObjectName("text_viewer_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.text_viewer_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_viewer_lbl = QtWidgets.QLabel(self.text_viewer_widget)
        self.text_viewer_lbl.setObjectName("text_viewer_lbl")
        self.verticalLayout_2.addWidget(self.text_viewer_lbl)
        self.tei_viewer = QtWidgets.QTextBrowser(self.text_viewer_widget)
        self.tei_viewer.setObjectName("tei_viewer")
        self.verticalLayout_2.addWidget(self.tei_viewer)
        self.general_horizontalLayout.addWidget(self.text_viewer_widget)
        self.general_horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_list_lbl.setText(_translate("MainWindow", "Image List"))
        self.drawMode_switch.setText(_translate("MainWindow", "Draw Mode"))
        self.import_images.setText(_translate("MainWindow", "Import Images"))
        self.remove_image.setText(_translate("MainWindow", "Remove Images"))
        self.view_tei.setText(_translate("MainWindow", "View TEI"))
        self.load_image.setText(_translate("MainWindow", "Load Image"))
        self.image_area_lbl.setText(_translate("MainWindow", "Image Area"))
        self.text_viewer_lbl.setText(_translate("MainWindow", "Text Viewer"))

